"""Set up the next model run: shard the questions and print the prompt.

    python prepare_run.py run-02          # write the shards, print what to do
    python prepare_run.py run-02 --size 25

Writes `runs/<label>/questions/questions-NN.jsonl`, each holding the id and text
of up to `--size` tests and nothing else. The expected files, facts, evidence and
reference answers stay out of them, because an agent that sees those is
measuring itself.

Then dispatch one agent per shard with the prompt in `runs/prompt.md`, verbatim,
and collect each shard's answers. When they are all in:

    python prepare_run.py run-02 --collect     # concatenate and sanity check
    python compare_runs.py                     # score it beside the others

`--collect` also writes `runs/<label>/corpus.json`, a digest of the generated
index the run read. See `corpus_digest` below for why.
"""
import hashlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
sys.path.insert(0, HERE)
import run_tests as R                                            # noqa: E402
import gxpaths                                                   # noqa: E402

RUNS = os.path.join(HERE, "runs")

# What an answering agent reads that can differ between two runs. The content
# slices cannot: step1 verifies on every build that they reassemble byte-exactly
# to the source, so a slice changing at all means the source revision changed,
# which is a bigger event than this file is trying to describe. Everything below
# is generated by build_all.py and does change, and `index/` is where a curated
# vocabulary edit or a new emitted section lands.
DIGESTED = ["index", "INDEX.md", "NAVIGATION.md"]


def corpus_digest():
    """Hash the generated index, per file and overall.

    A run's score is only comparable with another run's if both read the same
    corpus. That was learned the expensive way: `multi-ipsec-policy-nesting`
    failed runs 01, 02 and 04 and passed run 05, and reading that as a 3-in-5
    failure rate is wrong, because the Containment section in `entities.md` was
    added between run 04 and run 05 specifically to fix it. Three of those five
    runs could not have benefited. The rate silently mixed evidence from two
    different corpora.

    Deliberately not derived from git. Not every environment that runs this has
    a repository, and `run.json`'s hand-typed `corpus_commit` was never read by
    anything, which is what let the mix go unnoticed. This reads the files.

    Per file as well as overall, so a later comparison can say which index file
    moved rather than only that something did.
    """
    files = {}
    for entry in DIGESTED:
        path = gxpaths.docs_path(entry)
        if os.path.isdir(path):
            for name in sorted(os.listdir(path)):
                fp = os.path.join(path, name)
                if os.path.isfile(fp):
                    files[f"{entry}/{name}"] = _sha(fp)
        elif os.path.isfile(path):
            files[entry] = _sha(path)
    overall = hashlib.sha256(
        "".join(f"{k}:{v}\n" for k, v in sorted(files.items())).encode()
    ).hexdigest()[:12]
    return overall, files


def _sha(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()[:12]


def collect(label):
    d = os.path.join(RUNS, label)
    qdir = os.path.join(d, "questions")
    tests = {t["id"] for t in R.load_tests()}
    rows, seen = [], set()
    for fn in sorted(os.listdir(qdir)):
        if not fn.startswith("answers-"):
            continue
        for line in open(os.path.join(qdir, fn), encoding="utf-8"):
            if not line.strip():
                continue
            r = json.loads(line)
            if r["id"] in seen:
                sys.exit(f"duplicate answer for {r['id']}")
            seen.add(r["id"])
            rows.append(r)
    missing, extra = tests - seen, seen - tests
    if extra:
        sys.exit(f"answers for ids that are not tests: {sorted(extra)[:5]}")
    out = os.path.join(d, "answers.jsonl")
    with open(out, "w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps({"id": r["id"], "answer": r["answer"]},
                               ensure_ascii=False) + "\n")
    avg = sum(len(r["answer"]) for r in rows) // max(1, len(rows))
    print(f"wrote {out}: {len(rows)} answers, mean {avg} characters")
    if missing:
        print(f"  WARNING: {len(missing)} tests unanswered, e.g. {sorted(missing)[:5]}")

    # Written here rather than left to run.json, which is hand-copied from
    # run-01 and edited. Hand-typed metadata drifts; this is measured.
    overall, files = corpus_digest()
    cpath = os.path.join(d, "corpus.json")
    with open(cpath, "w", encoding="utf-8") as f:
        json.dump({"digest": overall, "files": files}, f, indent=2)
        f.write("\n")
    print(f"wrote {cpath}: index digest {overall}, {len(files)} files")
    print(f"  now write {os.path.join(d, 'run.json')} (copy run-01's and edit),"
          f"\n  then: python compare_runs.py")


def main():
    if len(sys.argv) < 2 or sys.argv[1].startswith("-"):
        sys.exit(__doc__)
    label = sys.argv[1]
    d = os.path.join(RUNS, label)
    if "--collect" in sys.argv:
        return collect(label)
    if os.path.exists(os.path.join(d, "answers.jsonl")):
        sys.exit(f"{label} already has answers.jsonl; delete it first if you mean to redo it")
    size = 25
    if "--size" in sys.argv:
        size = int(sys.argv[sys.argv.index("--size") + 1])

    tests = R.load_tests()
    qdir = os.path.join(d, "questions")
    os.makedirs(qdir, exist_ok=True)
    shards = [tests[i:i + size] for i in range(0, len(tests), size)]
    for n, sh in enumerate(shards, 1):
        with open(os.path.join(qdir, f"questions-{n:02d}.jsonl"), "w",
                  encoding="utf-8") as f:
            for t in sh:
                f.write(json.dumps({"id": t["id"], "question": t["question"]},
                                   ensure_ascii=False) + "\n")
    print(f"wrote {len(shards)} shards of up to {size} questions to {qdir}\n")
    print("Dispatch one agent per shard with runs/prompt.md verbatim, substituting:")
    print(f"   <SHARD PATH>   {os.path.join(qdir, 'questions-NN.jsonl')}")
    print(f"   <OUTPUT PATH>  {os.path.join(qdir, 'answers-NN.jsonl')}")
    print("\nThe prompt is fixed on purpose. A second run measures variance only if")
    print("the method is held constant; reword it and you have measured the prompt.")
    print(f"\nWhen every shard is in:  python prepare_run.py {label} --collect")
    return 0


if __name__ == "__main__":
    sys.exit(main())
