"""Curated layer: functional domains and query-vocabulary topics.

Domain assignment is one primary domain per command (topics carry the
cross-cutting relationships). Every assignment below was made by reading the
command's own description in the source document.
"""

DOMAIN_TITLES = {
    "cli-and-session": "CLI, sessions and scripting",
    "config-datastore": "Candidate config, commit, database and templates",
    "equipment-inventory": "Equipment, cards, ports, pluggables and inventory",
    "protection-redundancy": "Protection and switchover",
    "optical-layer0": "Layer 0 photonics: spectrum, amplifiers, degrees, OTDR",
    "transport-layer1": "Layer 1 transport: OTN, Ethernet and client facilities",
    "topology-discovery": "Topology, fiber connections and neighbor discovery",
    "ip-networking": "IP interfaces, routing protocols and DCN",
    "security-access-control": "Users, AAA and access control",
    "certificates-pki": "Certificates, PKI and SSH keys",
    "encryption-ipsec-macsec": "Encryption: IPsec/IKEv2, MACsec and secure entities",
    "management-protocols": "Management protocols, telemetry and third-party apps",
    "fault-alarms-logging": "Alarms, conditions and logging",
    "performance-monitoring": "Performance monitoring and statistics",
    "software-firmware-files": "Software, firmware, file transfer and ZTP",
    "system-node-time": "Node-level system, time and status",
}

DOMAINS = {
    "cli-and-session": [
        "add", "alias", "clear", "cli", "cli-session-config", "connect", "convert",
        "default", "delete", "edit", "exit", "expect", "export", "gshell", "help",
        "history", "kill-session", "message", "property", "run", "scheduled-task",
        "session", "set", "shell", "show", "simulate", "sleep", "task", "terminate",
        "tic", "toc", "top", "tree", "unalias", "up", "update", "?",
        "begin", "display", "exclude", "grep", "highlight", "include", "linenum",
        "more", "sort", "until",
    ],
    "config-datastore": [
        "activate-snapshot", "advanced-parameter", "apply-template", "commit",
        "config", "configure", "current-advanced-parameter", "database", "db-migrate",
        "db-protection-scheme", "diff", "discard-changes", "extended-config",
        "golden-advanced-parameter", "lock", "named-value-set", "recovery",
        "rollback", "show commit", "system-policies", "take-snapshot", "template",
        "template-group", "templates", "unlock", "validate",
    ],
    "equipment-inventory": [
        "capabilities", "card", "chassis", "console", "controller-card", "equipment",
        "equipment-policies", "equipment-templates", "fru-info", "inventory", "led",
        "port", "resources", "serdes", "serdes-template", "serdes-template-entry",
        "serial-console", "slot", "sub-component", "supported-card",
        "supported-chassis", "supported-port", "supported-slot", "supported-tom",
        "supported-tom-power", "tom", "tom-type", "unprovisioned-inventory", "usb",
    ],
    "protection-redundancy": [
        "manual-switchover", "protection", "protection-group", "protection-switch",
        "protection-unit",
    ],
    "optical-layer0": [
        "adg", "amplifier", "amplifier-raman", "ase-idler-service", "ase-idler-source",
        "calibrate", "degree", "direction", "dsc", "dsc-group", "gadt", "gapt", "gcmt",
        "golden-carrier-mode", "l0-capabilities", "mc", "mc-f", "modules-adg",
        "modules-degree", "monitored-channel", "nmc", "nmc-f", "oadm-capabilities",
        "oc", "ochm", "ocm-channel", "ocm-mp", "ocm-ptp", "oms", "ops",
        "optical-carrier", "optical-channel", "optical-ptp", "optical-switch", "osc",
        "otdr", "otdr-ptp", "ots", "ots-diagnostics", "ots-r", "ots-r-auto-otdr",
        "oxcon", "profile-control", "pump", "pump-power", "raman-calibration", "rsc", "spectrum", "spectrum-control",
        "spectrum-monitoring", "super-channel", "super-channel-group",
        "supported-carrier-mode", "supported-gain-range", "supported-power-profile",
    ],
    "transport-layer1": [
        "bert", "cid-ptp", "eth-zr", "ethernet", "facilities", "fc", "flexo",
        "flexo-group", "high-speed-monitoring", "interlaken", "L2-bridge", "line-ptp",
        "network-xconnect", "nw-xconnect", "odu", "odu-diagnostics", "otu",
        "otu-diagnostics", "stm", "trib-ptp", "xcon",
    ],
    "topology-discovery": [
        "cable-id", "cable-id-path", "cable-id-status", "carrier-neighbor",
        "connection-ports", "custom-tlv", "external-fiber-connection",
        "fiber-connection", "icdp", "inci", "inci-neighbor", "interface-neighbor",
        "links", "lldp", "lldp-local-info", "lldp-neighbor", "lldp-port-statistics",
        "nct-connection", "sndp", "submarine-link", "supporting-fiber-connection",
        "topology", "verify",
    ],
    "ip-networking": [
        "bgp-instance", "bgp-neighbor", "bgp-network", "comm-channel", "comm-eth",
        "dhcp-relay", "dns", "dns-server", "if-dhcp-relay", "interface",
        "ip-monitoring", "ipv4-address", "ipv4-static-route", "ipv6-address",
        "ipv6-static-route", "management-address", "management-address-local",
        "networking", "networking-services", "next-hop", "ospf", "ospf-area",
        "ospf-area-range", "ospf-instance", "ospf-interface", "ospf-neighbor",
        "ospfv3-ipsec-security-association", "ping", "protocols", "rib", "route",
        "routing", "supporting-interface", "traceroute", "vrf",
    ],
    "security-access-control": [
        "aaa-server", "aaa-statistics", "ace", "acl", "access-control-list",
        "access-rule", "access-rule-list", "auth-key", "authorization", "password",
        "security", "security-policies", "user", "user-data", "user-group",
    ],
    "certificates-pki": [
        "cdp", "cert-gen", "cert-to-name", "certificate", "crl", "csr-gen",
        "display-cert", "est", "est-ca", "est-server", "import-certificate", "ISK",
        "key-replacement-package", "KRK", "local-certificate", "ocsp-server",
        "peer-certificate", "ssh", "ssh-authorized-key", "ssh-host-key", "ssh-keygen",
        "ssh-known-host", "trusted-certificate",
    ],
    "encryption-ipsec-macsec": [
        "additional-key-exchange", "data-path-encryption", "encryption-algorithm",
        "ike-sa-proposal", "ikev2", "ikev2-local-instance", "ikev2-peer",
        "ipsec-sa-proposal", "ipsec-sa-re-key", "ipsec-spd-entry",
        "ipsec-traffic-selector", "local-ports", "local-subnet", "macsec-entity",
        "macsec-mka", "mka-policy", "re-auth", "re-key", "remote-ports",
        "remote-subnet", "sc-rx", "sc-tx", "secure-application", "secure-entity",
        "secure-entity-sa-proposal", "security-policy-database",
    ],
    "management-protocols": [
        "app", "appctl", "call-home", "current-subscription", "data-model",
        "dial-out-server", "grpc", "netconf", "restconf", "snmp", "snmp-community",
        "snmp-target", "snmpv3-user", "subscription-path", "subscriptions",
        "telemetry", "third-party-app",
    ],
    "fault-alarms-logging": [
        "alarm", "alarm-control", "alarm-inventory", "alarm-severity-entry",
        "alarm-severity-profile", "current-alarms", "get-conditions", "log",
        "log-console", "log-console-facility-filter", "log-file",
        "log-file-facility-filter", "log-server", "log-server-facility-filter",
        "set-alarm-state", "statistics", "syslog",
    ],
    "performance-monitoring": [
        "pm", "pm-catalog", "pm-control", "pm-control-entry", "pm-parameter",
        "pm-profile", "pm-profile-entry", "pm-resource", "pm-threshold",
        "pm-threshold-profile",
    ],
    "software-firmware-files": [
        "activate", "bootstrap", "cancel-upgrade", "change-ztp-mode", "current-fw",
        "download", "downloaded-image", "downloads", "file", "file-operation",
        "file-server", "file-type", "http-file-server", "manifest", "packaged-fw",
        "prepare-upgrade", "recover-mode", "software-load", "software-location",
        "sw-component", "sw-container", "sw-control-rule", "sw-management",
        "sw-service", "sw-subcomponent", "subtype-constraint", "swversion",
        "third-party-fw", "transfer", "transfer-status", "upgrade-status", "upload",
        "ztp",
    ],
    "system-node-time": [
        "clock", "ne", "ne-function", "ntp", "ntp-key", "ntp-server",
        "ntp-server-status", "restart", "set-time", "status", "system", "time",
        "uptime",
    ],
}

# topic -> (query vocabulary used for grounding, commands)
TOPICS = [
    ("Zero touch provisioning (ZTP)", ["ztp", "zero touch", "bootstrap", "commissioning", "brand new node",
      "first admin", "neighbour node"],
     ["ztp", "change-ztp-mode", "bootstrap"]),
    ("Software upgrade", ["upgrade", "software load", "activate", "swversion", "software version",
      "software label", "prepare", "install", "running software",
      "software on", "what software", "versions"],
     ["prepare-upgrade", "activate", "cancel-upgrade", "upgrade-status", "swversion",
      "software-load", "software-location", "sw-management", "downloaded-image",
      "manifest", "subtype-constraint", "sw-component", "sw-subcomponent",
      "software-location", "prepare-upgrade", "swversion"]),
    ("Firmware (FW) management", ["firmware", "fw"],
     ["current-fw", "packaged-fw", "third-party-fw", "activate"]),
    ("File transfer and file servers", ["download", "upload", "file server", "transfer", "sftp", "directory",
      "proxy", "export", "diagnostic log", "debug log", "pull onto", "get off"],
     ["download", "upload", "transfer", "transfer-status", "file", "file-operation",
      "file-server", "http-file-server", "file-type", "downloads"]),
    ("Database backup, snapshot and restore", ["snapshot", "database", "recovery", "migrate", "replacement controller",
      "chassis storage", "restore", "backup"],
     ["database", "take-snapshot", "activate-snapshot", "db-migrate",
      "db-protection-scheme", "recovery", "recover-mode"]),
    ("Candidate configuration, commit and rollback",
     ["candidate", "commit", "rollback", "datastore", "discard", "staged",
      "configuration mode", "exclusive", "lock", "throw away", "abandon",
      "changing configuration", "write access", "mastership"],
     ["configure", "commit", "show commit", "rollback", "discard-changes",
      "validate", "diff", "lock", "unlock", "system-policies", "config"]),
    ("Configuration templates and defaults",
     ["template", "default", "named-value", "advanced parameter",
      "extended config", "non-standard"],
     ["template", "template-group", "templates", "apply-template", "default",
      "named-value-set", "advanced-parameter", "current-advanced-parameter",
      "golden-advanced-parameter", "gapt", "extended-config", "property",
      "equipment-templates"]),
    ("Alarms and conditions", ["alarm", "condition", "severity", "acknowledge"],
     ["alarm", "current-alarms", "alarm-control", "alarm-inventory",
      "alarm-severity-profile", "alarm-severity-entry", "set-alarm-state",
      "get-conditions", "simulate"]),
    ("Syslog and logging",
     ["log", "syslog", "facility", "severity", "console", "informational",
      "debug", "collector", "forward", "message", "rotation"],
     ["log", "syslog", "log-file", "log-file-facility-filter", "log-server",
      "log-server-facility-filter", "log-console", "log-console-facility-filter"]),
    ("Performance monitoring, PM bins and thresholds",
     ["pm", "performance", "threshold", "tca", "bin", "counter", "limit",
      "errored second", "supervision", "gauge"],
     ["pm", "pm-catalog", "pm-control", "pm-control-entry", "pm-parameter",
      "pm-profile", "pm-profile-entry", "pm-resource", "pm-threshold",
      "pm-threshold-profile", "statistics", "high-speed-monitoring"]),
    ("Certificates and PKI",
     ["certificate", "x509", "csr", "crl", "ocsp", "est", "ca"],
     ["certificate", "local-certificate", "trusted-certificate", "peer-certificate",
      "import-certificate", "display-cert", "csr-gen", "cert-gen", "crl", "cdp",
      "ocsp-server", "est", "est-ca", "est-server", "cert-to-name"]),
    ("SSH keys and known hosts", ["ssh", "key pair", "known host", "host key", "authorized key",
      "public key", "log in with", "keygen"],
     ["ssh", "ssh-keygen", "ssh-host-key", "ssh-authorized-key", "ssh-known-host"]),
    ("Image signing and root keys", ["image signing", "root key", "isk", "krk",
                                     "key replacement"],
     ["ISK", "KRK", "key-replacement-package"]),
    ("MACsec", ["macsec", "mka", "secure channel", "sak"],
     ["macsec-entity", "macsec-mka", "mka-policy", "sc-rx", "sc-tx"]),
    ("IPsec and IKEv2", ["ipsec", "ikev2", "ike", "security association", "traffic selector",
      "re-key", "security policy", "spd", "matching traffic", "tunnel"],
     ["ike-sa-proposal", "ikev2", "ikev2-local-instance", "ikev2-peer",
      "ipsec-sa-proposal", "ipsec-sa-re-key", "ipsec-spd-entry",
      "ipsec-traffic-selector", "security-policy-database", "local-subnet",
      "remote-subnet", "local-ports", "remote-ports", "re-key", "re-auth",
      "additional-key-exchange", "encryption-algorithm",
      "ospfv3-ipsec-security-association"]),
    ("Data path / Layer 1 encryption",
     ["encryption", "secure entity", "secure application", "data-path",
      "encrypted wavelength", "digital identity", "presents", "mutual"],
     ["data-path-encryption", "secure-entity", "secure-entity-sa-proposal",
      "secure-application", "peer-certificate", "local-certificate"]),
    ("Users, passwords and user groups",
     ["user", "password", "group", "privilege", "login", "lockout", "account",
      "complexity", "minimum length"],
     ["user", "user-group", "user-data", "password", "authorization",
      "session", "kill-session", "security-policies"]),
    ("AAA, TACACS+ and RADIUS", ["aaa", "tacacs", "radius", "authentication"],
     ["aaa-server", "aaa-statistics", "authorization", "auth-key", "cert-to-name"]),
    ("Access control lists and rules",
     ["acl", "access control", "access rule", "ace", "permit", "deny", "rule",
      "packet filter", "filter rule", "firewall"],
     ["acl", "ace", "access-control-list", "access-rule", "access-rule-list",
      "security", "security-policies", "authorization"]),
    ("OSPF routing", ["ospf", "area", "lsa", "adjacency"],
     ["ospf", "ospf-instance", "ospf-area", "ospf-area-range", "ospf-interface",
      "ospf-neighbor", "ospfv3-ipsec-security-association"]),
    ("BGP routing", ["bgp", "peer", "autonomous system", "advertise", "announce", "upstream as",
      "as "],
     ["bgp-instance", "bgp-neighbor", "bgp-network"]),
    ("Static routes, RIB and VRF", ["static route", "route", "rib", "vrf", "next hop",
      "routing information base", "routing instance", "address family",
      "forwarding table"],
     ["ipv4-static-route", "ipv6-static-route", "route", "rib", "routing",
      "next-hop", "vrf"]),
    ("IP addressing and interfaces", ["ip address", "ipv4", "ipv6", "interface", "subnet", "mtu",
      "management ethernet", "network service", "source address", "negotiat",
      "bridge",
      "use-as-source", "uses as its source",
      "duplex"],
     ["interface", "ipv4-address", "ipv6-address", "supporting-interface",
      "networking", "networking-services", "comm-eth", "comm-channel",
      "L2-bridge", "ip-monitoring"]),
    ("DNS and DHCP", ["dns", "dhcp", "domain name", "relay", "name server"],
     ["dns", "dns-server", "dhcp-relay", "if-dhcp-relay"]),
    ("Reachability tests", ["ping", "traceroute", "echo", "monitoring", "reachability", "trace",
      "hops", "unreachable", "far end"],
     ["ping", "traceroute", "ip-monitoring"]),
    ("LLDP and neighbor discovery",
     ["lldp", "neighbor", "neighbour", "discovery", "tlv", "icdp", "sndp",
      "management address", "advertising", "inci", "discover", "far end",
      "stale"],
     ["lldp", "lldp-local-info", "lldp-neighbor", "lldp-port-statistics",
      "custom-tlv", "icdp", "sndp", "carrier-neighbor", "interface-neighbor",
      "inci", "inci-neighbor", "management-address",
      "management-address-local", "topology", "carrier-neighbor"]),
    ("Topology and fiber connections",
     ["topology", "fiber", "fibre", "cable", "link", "connection", "connectiv"],
     ["topology", "links", "fiber-connection", "external-fiber-connection",
      "supporting-fiber-connection", "connection-ports", "submarine-link",
      "nct-connection"]),
    ("CableID fiber verification", ["cableid", "cable-id", "verify", "fibre verification", "fiber verification",
      "progress"],
     ["cable-id", "cable-id-path", "cable-id-status", "verify", "cid-ptp"]),
    ("OTDR and fiber diagnostics", ["otdr", "reflect", "fiber", "fibre", "trace", "scan"],
     ["otdr", "otdr-ptp", "ots-r-auto-otdr", "ots-diagnostics"]),
    ("Amplifiers, gain and Raman pumps",
     ["amplifier", "gain", "raman", "pump", "tilt"],
     ["amplifier", "amplifier-raman", "pump", "pump-power", "raman-calibration",
      "calibrate", "supported-gain-range", "rsc", "ne-function"]),
    ("Spectrum, wavelength and channels",
     ["spectrum", "frequency", "wavelength", "channel", "carrier", "thz"],
     ["spectrum", "spectrum-control", "spectrum-monitoring", "mc", "mc-f", "nmc",
      "nmc-f", "oc", "optical-carrier", "optical-channel", "optical-ptp",
      "super-channel", "super-channel-group", "monitored-channel", "ocm-channel",
      "ocm-mp", "ocm-ptp", "ochm", "supported-carrier-mode",
      "golden-carrier-mode", "gadt", "gcmt"]),
    ("Optical sections OTS / OMS / OPS / OSC",
     ["ots", "oms", "ops", "osc", "supervisory", "section"],
     ["ots", "ots-r", "oms", "ops", "osc", "ots-diagnostics"]),
    ("ROADM degrees, add/drop groups and switching",
     ["degree", "adg", "add/drop", "roadm", "oadm", "switch", "cross connection",
      "ase", "idler", "photonic", "layer 0", "l0"],
     ["degree", "adg", "modules-degree", "modules-adg", "oadm-capabilities",
      "optical-switch", "oxcon", "direction", "l0-capabilities",
      "ase-idler-service", "ase-idler-source"]),
    ("Optical power control and profiles",
     ["power", "attenuation", "profile", "target"],
     ["profile-control", "supported-power-profile", "supported-tom-power",
      "spectrum-control", "amplifier"]),
    ("OTN: ODU, OTU and cross-connects",
     ["odu", "otu", "otn", "cross connect", "xcon", "tti", "trace", "sapi",
      "dapi", "flexo", "gcc", "mismatched"],
     ["odu", "otu", "odu-diagnostics", "otu-diagnostics", "xcon", "nw-xconnect",
      "network-xconnect", "flexo", "flexo-group"]),
    ("Ethernet and client facilities",
     ["ethernet", "client", "fibre channel", "interlaken", "stm", "zr", "sdh",
      "sonet", "termination point", "auto in service", "tributary", "bridge",
      "l2-bridge"],
     ["ethernet", "eth-zr", "fc", "interlaken", "stm", "trib-ptp", "line-ptp",
      "facilities"]),
    ("Loopbacks, test signals and BERT",
     ["loopback", "test signal", "bert", "prbs", "diagnostic"],
     ["bert", "odu-diagnostics", "otu-diagnostics", "ots-diagnostics", "stm",
      "ethernet", "odu"]),
    ("Cards, slots, chassis and pluggables",
     ["card", "slot", "chassis", "tom", "pluggable", "fru", "equipment",
      "console", "baud", "craft", "standby controller", "controller"],
     ["card", "slot", "chassis", "equipment", "controller-card", "port", "tom",
      "tom-type", "sub-component", "fru-info", "led", "usb", "console",
      "serial-console", "resources", "equipment-policies", "controller-card",
      "usb", "slot", "sub-component"]),
    ("Inventory and capabilities",
     ["inventory", "capabilit", "supported", "supports", "part number", "card type",
      "chassis type", "form factor", "breakout", "phy mode", "blank",
      "compatib", "redundancy supported", "capable of", "what can"],
     ["inventory", "unprovisioned-inventory", "capabilities", "supported-card",
      "supported-chassis", "supported-slot", "supported-port", "supported-tom",
      "supported-tom-power", "tom-type", "fru-info", "l0-capabilities",
      "oadm-capabilities", "subtype-constraint"]),
    ("SerDes and TOM templates", ["serdes", "template", "tom"],
     ["serdes", "serdes-template", "serdes-template-entry", "equipment-templates",
      "supported-tom", "supported-tom-power"]),
    ("Equipment protection and switchover",
     ["protect", "switchover", "switch", "redundan", "working", "standby",
      "y-cable", "sncp"],
     ["protection", "protection-group", "protection-switch", "protection-unit",
      "manual-switchover"]),
    ("NTP and system time", ["ntp", "time", "clock", "timezone"],
     ["ntp", "ntp-key", "ntp-server", "ntp-server-status", "clock", "set-time",
      "time"]),
    ("SNMP", ["snmp", "community", "trap", "v3"],
     ["snmp", "snmp-community", "snmp-target", "snmpv3-user"]),
    ("NETCONF, RESTCONF, gNMI and YANG",
     ["netconf", "restconf", "grpc", "gnmi", "yang", "data model"],
     ["netconf", "restconf", "grpc", "data-model", "cli", "convert"]),
    ("Telemetry and subscriptions",
     ["telemetry", "subscri", "stream", "dial-out", "call home", "dial out",
      "management system", "retry timer"],
     ["telemetry", "subscriptions", "current-subscription", "subscription-path",
      "dial-out-server", "call-home"]),
    ("Scripting, tasks and automation",
     ["script", "task", "schedule", "variable", "alias", "expect", "property",
      "card property", "on demand", "card-level"],
     ["run", "task", "scheduled-task", "expect", "export", "sleep", "message",
      "alias", "unalias", "simulate", "property"]),
    ("Third-party applications and containers",
     ["third party", "third-party", "app", "container", "shell", "service",
      "software service", "restarting", "daemon"],
     ["app", "appctl", "third-party-app", "third-party-fw", "gshell", "shell",
      "sw-container", "sw-service", "sw-control-rule"]),
    ("Node, NE-level settings and status",
     ["network element", "system", "status", "uptime", "restart", "node type",
      "node-type", "ila", "oadm", "xpdr", "in-line amplifier", "load average",
      "ne-name", "site", "location"],
     ["ne", "ne-function", "system", "status", "uptime", "restart", "resources",
      "chassis"]),
    ("Multi-chassis and node controller",
     ["multi-chassis", "node controller", "nct", "chassis"],
     ["nct-connection", "unprovisioned-inventory", "chassis",
      "management-address", "management-address-local"]),
    ("Laser shutdown and transmit control",
     ["laser", "shutdown", "propagate-shutdown", "als", "squelch"],
     ["optical-carrier", "optical-ptp", "fc", "trib-ptp", "ots", "otdr"]),
    ("Environmental: fans, temperature, voltage",
     ["fan", "temperature", "voltage", "environment", "cooling", "locator",
      "led", "lamp test"],
     ["chassis", "card", "pm", "status", "trib-ptp", "led", "activate",
      "terminate"]),
    ("Serial numbers, CLEI and FRU identification",
     ["serial number", "serial-number", "clei", "part number", "manufactur"],
     ["inventory", "unprovisioned-inventory", "fru-info", "chassis", "card",
      "sub-component"]),
    ("Restart, reboot and recovery",
     ["reboot", "restart", "reset", "reload", "recover"],
     ["restart", "recover-mode", "recovery", "manual-switchover", "card",
      "chassis"]),
    ("Factory reset, wipe and decommissioning",
     ["factory reset", "factory-reset", "wipe", "full-wipe", "decommission",
      "erase", "secure wipe"],
     ["system", "database", "clear", "recovery", "take-snapshot"]),
    ("Span loss, dispersion and optical line characterisation",
     ["span loss", "span-loss", "span", "dispersion", "cd", "pmd", "reach",
      "fiber type", "fibre", "lossy"],
     ["ots", "ots-r", "amplifier", "otdr", "otdr-ptp", "ots-r-auto-otdr",
      "optical-carrier", "raman-calibration"]),
    ("Signal quality: OSNR, FEC and error counts",
     ["osnr", "fec", "pre-fec", "ber", "q-factor", "error", "signal quality"],
     ["status", "pm", "pm-parameter", "bert", "otu-diagnostics",
      "odu-diagnostics", "eth-zr", "optical-carrier", "dsc-group"]),
    ("CLI navigation, output filtering and help",
     ["navigat", "prompt", "help", "pipe", "filter", "tree", "terminal",
      "rows", "columns", "cli session", "logged into", "broadcast",
      "alarm columns", "create entity", "managed entity", "confirmation",
      "hop to", "long-running", "stop", "which entities", "creatable"],
     ["edit", "top", "up", "tree", "history", "alias", "unalias", "help", "?",
      "begin", "display", "exclude", "grep", "highlight", "include", "linenum",
      "more", "sort", "until", "tic", "toc", "cli", "cli-session-config",
      "add", "clear", "connect", "message", "terminate", "exit"]),
]
